import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import type { RuneConfig } from "../core/define-config";
import type { CommandOptionField } from "../core/field-types";
import type { CommandManifest, CommandManifestCommandNode } from "../manifest/manifest-types";
import type { ProjectDirectories } from "../project/project-files";

import {
  validateConfigOptionsForSync,
  validateGlobalOptionsForCommand,
} from "../core/global-options";
import { defaultLoadCommand } from "../runtime/load-command";
import { loadRuneConfig } from "../runtime/load-rune-config";
import { bundleCommandForRun, bundleConfigForRun } from "./bundle-for-run";

const RUNE_DIRECTORY_NAME = ".rune";
const GLOBAL_OPTIONS_TYPES_FILENAME = "global-options.d.ts";
const SYNC_DIRECTORY_NAME = path.join(RUNE_DIRECTORY_NAME, "sync");

export interface RegenerateGlobalOptionsTypesOptions {
  readonly projectRoot: string;
  readonly configPath?: string | undefined;
}

export interface ValidateGlobalOptionsOptions extends RegenerateGlobalOptionsTypesOptions {
  readonly directories: ProjectDirectories;
  readonly manifest?: CommandManifest | undefined;
}

export interface ValidateGlobalOptionsResult {
  readonly config?: RuneConfig | undefined;
}

export async function regenerateGlobalOptionsTypes(
  options: RegenerateGlobalOptionsTypesOptions,
): Promise<void> {
  await writeGlobalOptionsTypes(options.projectRoot, options.configPath);
}

export async function validateGlobalOptions(
  options: ValidateGlobalOptionsOptions,
): Promise<ValidateGlobalOptionsResult> {
  await regenerateGlobalOptionsTypes(options);

  if (options.configPath === undefined) {
    return { config: undefined };
  }

  const syncDirectory = await prepareSyncDirectory(options.projectRoot);
  const bundledConfigPath = await bundleConfigForRun(
    options.projectRoot,
    syncDirectory,
    options.configPath,
  );
  const config = await loadRuneConfig(bundledConfigPath, "built rune.config.ts");
  const globalOptions = config.options;

  await validateConfigOptionsForSync(globalOptions);

  if (options.manifest) {
    await validateGlobalOptionsForManifest({
      projectRoot: options.projectRoot,
      sourceDirectory: options.directories.sourceDirectory,
      syncDirectory,
      manifest: options.manifest,
      globalOptions,
    });
  }

  return { config };
}

async function writeGlobalOptionsTypes(
  projectRoot: string,
  configPath: string | undefined,
): Promise<void> {
  const runeDirectory = path.join(projectRoot, RUNE_DIRECTORY_NAME);
  await mkdir(runeDirectory, { recursive: true });
  await writeFile(
    path.join(runeDirectory, GLOBAL_OPTIONS_TYPES_FILENAME),
    renderGlobalOptionsTypes(configPath !== undefined),
  );
}

function renderGlobalOptionsTypes(hasConfig: boolean): string {
  const importLines = hasConfig
    ? 'import type config from "../rune.config";\nimport type { InferConfigOptions } from "@rune-cli/rune";\n\n'
    : "";
  const extendsClause = hasConfig ? " extends InferConfigOptions<typeof config>" : "";

  return `// This file is generated by rune sync. Do not edit.
${importLines}declare module "@rune-cli/rune" {
  interface RuneConfigOptions${extendsClause} {}
}
`;
}

async function prepareSyncDirectory(projectRoot: string): Promise<string> {
  const syncDirectory = path.join(projectRoot, SYNC_DIRECTORY_NAME);
  await rm(syncDirectory, { recursive: true, force: true });
  await mkdir(syncDirectory, { recursive: true });
  return syncDirectory;
}

async function validateGlobalOptionsForManifest(options: {
  readonly projectRoot: string;
  readonly sourceDirectory: string;
  readonly syncDirectory: string;
  readonly manifest: CommandManifest;
  readonly globalOptions: readonly CommandOptionField[];
}): Promise<void> {
  for (const node of options.manifest.nodes) {
    if (node.kind !== "command") {
      continue;
    }

    const builtSourceFilePath = await bundleCommandForRun(
      options.projectRoot,
      options.sourceDirectory,
      options.syncDirectory,
      node,
    );
    const command = await defaultLoadCommand(replaceNodeSourcePath(node, builtSourceFilePath));
    validateGlobalOptionsForCommand(options.globalOptions, command);
  }
}

function replaceNodeSourcePath(
  node: CommandManifestCommandNode,
  sourceFilePath: string,
): CommandManifestCommandNode {
  return {
    ...node,
    sourceFilePath,
  };
}
