import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import runePackageJson from "../packages/rune/package.json" with { type: "json" };

function ensureString(value: unknown, description: string): string {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`Expected ${description} to be a non-empty string`);
  }

  return value;
}

async function main(): Promise<void> {
  const scriptsDirectory = fileURLToPath(new URL(".", import.meta.url));
  const repositoryRoot = path.resolve(scriptsDirectory, "..");

  const scaffoldedNodeVersion = ensureString(
    runePackageJson.engines?.node,
    "packages/rune/package.json engines.node",
  );
  const scaffoldedRuneVersion = `^${ensureString(
    runePackageJson.version,
    "packages/rune/package.json version",
  )}`;

  const outputPath = path.join(
    repositoryRoot,
    "packages",
    "create-rune-app",
    "src",
    "generated",
    "scaffold-versions.ts",
  );
  const outputContents = [
    "// Generated by scripts/sync-scaffold-versions.ts. Do not edit manually.",
    `export const SCAFFOLDED_NODE_VERSION = ${JSON.stringify(scaffoldedNodeVersion)};`,
    `export const SCAFFOLDED_RUNE_VERSION = ${JSON.stringify(scaffoldedRuneVersion)};`,
    "",
  ].join("\n");

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, outputContents);
}

await main();
