name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@8ecb39174989ce55af90f45cf55b02738599831d # v1.6.0
        with:
          node-version: "24"
          cache: true

      - name: Install dependencies
        run: vp install --frozen-lockfile

      - name: Build packages
        run: vp run --filter './packages/*' build

      - name: Run Vite+ check
        run: vp run --filter './packages/*' check

      - name: Run ls-lint
        run: vpx ls-lint

      - name: Run knip
        run: vpx knip

      - name: Run sherif
        run: vpx sherif

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@8ecb39174989ce55af90f45cf55b02738599831d # v1.6.0
        with:
          node-version: "24"
          cache: true

      - name: Install dependencies
        run: vp install --frozen-lockfile

      - name: Build packages
        run: vp run --filter './packages/*' build

      - name: Run tests
        run: vp run --filter './packages/*' test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup pnpm
        uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v6.0.4

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@8ecb39174989ce55af90f45cf55b02738599831d # v1.6.0
        with:
          node-version: "24"
          cache: true

      - name: Install dependencies
        run: vp install --frozen-lockfile

      - name: Build packages
        run: vp run --filter './packages/*' build

      - name: Run publint
        run: vpx publint ./packages/rune

      - name: Run attw
        run: vpx attw --pack --profile esm-only ./packages/rune
