name: Publish Pull Request

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@8ecb39174989ce55af90f45cf55b02738599831d # v1.6.0
        with:
          node-version: "24"
          cache: true

      - name: Install dependencies
        run: vp install --frozen-lockfile

      - name: Build packages
        run: vp run --filter './packages/*' build

      - name: Publish
        run: vpx pkg-pr-new publish --pnpm './packages/create-rune-app' './packages/rune'
